### ISSUE TITLE
pas capable de créer un plan d'intervention patient

### ISSUE THREAD

**Issue by Sarmar57** [Sarmar57/mepp#1]
J'ai créé un profil patient et je tente de lui créer un nouveau plan d'intervention, or, qd j'appuie sur "enregistrer", ça me dit "bad request". Idem qd j'essaie de créer un PI à partir du système. 
En bref, je ne peux pas créer de PI :-(
![2022-01-05 (4)](https://user-images.githubusercontent.com/77115758/148327472-aa4092c7-b51c-41b8-9ddf-1082f9a762d8.png)
![2022-01-05 (5)](https://user-images.githubusercontent.com/77115758/148327473-5f31a696-4f08-4b8c-b8aa-ce7c5cd14909.png)

**Comment by noliveleger** [comment]
@Sarmar57 , est-ce que ce problème a été résolu? 
Il me semble que oui ! Si oui, je ne la transférerai pas vers le repo officiel de MEPP
