### ISSUE TITLE
Bug avec Deep Ar

### ISSUE THREAD

**Issue by Sarmar57** [Sarmar57/mepp#3]
L'image du miroir flash sans arrêt

https://user-images.githubusercontent.com/77115758/154312000-7696e9bd-6317-4bc7-846d-620911d6df02.mp4

**Comment by noliveleger** [comment]
@Sarmar57 , je suis d'accord avec @fperreault , il faut éviter les changements de lumière trop intenses pour la webcam. 
Comme le filtre appliqué est recalculé en temps réel, si la lecture de quantité de lumière change constamment pour la webcam (ce qui arrive avec un contre jour), le problème apparaitra tout le temps.
